### ISSUE TITLE
301 redirect cached in browser

### ISSUE THREAD

**Issue by markuspeloquin** [marshill/marshill.github.io#2]
Unfortunately, http://marshill.com used to respond with 301 Moved Permanently to https://marshill.com. It seems like Chrome cached this permanently, so I couldn't see the HTTP-only website in my browser. It also doesn't look like GitHub supports HTTPS, unfortunately, so there may be no solution.

I guess the takeaway is to give 301s expiration dates or TTLs. Apparently `Cache-Control` and `Expires` would both do it.

**Comment by joeday** [comment]
I think you're right Marcus, there may be no solution other than using a different browser. Terrible answer and terrible support, I know. Thanks for at least taking the time to bring it up and I'm sorry I can't offer a better solution.
